name: Internship Monitor

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-internships:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Check Trackr
        env:
          TRACKR_EMAIL: ${{ secrets.TRACKR_EMAIL }}
          TRACKR_EMAIL_PASSWORD: ${{ secrets.TRACKR_EMAIL_PASSWORD }}
          TRACKR_EMAIL_TO: ${{ secrets.TRACKR_EMAIL_TO }}
        run: |
          python tracker.py

      - name: Save latest internship state
        run: |
          git config user.name "internship-tracker-bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add internships_seen.json

          if git diff --cached --quiet; then
            echo "No state changes"
          else
            git commit -m "Update internship state"
            git push
          fi
